[server]
maxUploadSize = 100
maxMessageSize = 100
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#ff6b6b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[browser]
gatherUsageStats = false 